date: "2020-01-02"
detector: "e2w_out"
path: "data/sim_intermediate_data/"
pathout: "data/sim_data/"
pathin: "data/calibration_data/"
network_file: "data/map/Hornsgatan.net.xml"
hornsgatan_home: "/home/kaveh/Hornsgatan/"
init_number: 100
